- id: '1572905926846'
  alias: Light Hall Toggle
  description: ''
  trigger:
  - device_id: 1b01f0993b5a4ba686281fed7fdea33e
    domain: deconz
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - data:
      entity_id:
      - light.hall_1_2
      - light.hall_2_2
      - light.hall_4_2
      - light.hall_5_2
      - light.hall_6
      - light.skogang_1_2
      - light.skogang_2_2
      - light.skogang_3_2
      - light.entre_2
    service: light.toggle
- id: '1572906572264'
  alias: Hall Dim up
  description: ''
  trigger:
  - device_id: 1b01f0993b5a4ba686281fed7fdea33e
    domain: deconz
    platform: device
    subtype: dim_up
    type: remote_button_long_press
  condition: []
  action:
  - alias: ''
    data_template:
      brightness: '{% set bri = state_attr("light.hall_6", "brightness") | int %}
        {{ [bri+30, 249] | min }}'
      entity_id:
        - light.skogang_1_2
        - light.skogang_2_2
        - light.skogang_3_2
        - light.hall_1_2
        - light.hall_2_2
        - light.hall_4_2
        - light.hall_5_2
        - light.hall_6
        - light.entre_2
    service: light.turn_on
- id: '1572906572164'
  alias: Hall Dim Down
  description: ''
  trigger:
  - device_id: 1b01f0993b5a4ba686281fed7fdea33e
    domain: deconz
    platform: device
    subtype: dim_down
    type: remote_button_long_press
  condition: []
  action:
  - alias: ''
    data_template:
      brightness: '{% set bri = state_attr("light.hall_6", "brightness") | int %}
        {{ [bri-30, 0] | max }}'
      entity_id:
        - light.skogang_1_2
        - light.skogang_2_2
        - light.skogang_3_2
        - light.hall_1_2
        - light.hall_2_2
        - light.hall_4_2
        - light.hall_5_2
        - light.hall_6
        - light.entre_2
    service: light.turn_on
