- id: '1574633872450'
  alias: Kjøkkenlys på
  description: ''
  trigger:
  - device_id: 0195134ee8c64a448e7de244abfdd687
    domain: light
    entity_id: light.kjokken_spot_1
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_on
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
    entity_id: light.zmnhhdx_mini_dimmer_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1574633914308'
  alias: Kjøkkenlys av
  description: ''
  trigger:
  - device_id: 0195134ee8c64a448e7de244abfdd687
    domain: light
    entity_id: light.kjokken_spot_1
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_off
  - device_id: 30d08d4c4a154e94852fa7d6d643bd35
    domain: light
    entity_id: light.zmnhhdx_mini_dimmer_level
    type: turn_off
  mode: parallel
  max: 10
- id: '1575295351793'
  alias: Utelys på
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - brightness_pct: 100
    device_id: 3656363d604841b282956ca4b47f4548
    domain: light
    entity_id: light.trapp_1
    type: turn_on
  - brightness_pct: 100
    device_id: f28dc05efd94407e9ec6b17d332fe29b
    domain: light
    entity_id: light.trapp_2
    type: turn_on
  - brightness_pct: 100
    device_id: b397071e15264940ae3d736547e15896
    domain: light
    entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_806lm_f0d83cfe_level_on_off
    type: turn_on
  - brightness_pct: 100
    device_id: dccd0bc1a092400794e266fb28c3a8d2
    domain: light
    entity_id: light.takterasse_1
    type: turn_on
  - brightness_pct: 100
    device_id: 69f6c1e792734102b374208260fe84d8
    domain: light
    entity_id: light.takterasse_2
    type: turn_on
- id: '1575295359193'
  alias: Utelys av
  description: ''
  trigger:
  - event: sunrise
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - device_id: 3656363d604841b282956ca4b47f4548
    domain: light
    entity_id: light.trapp_1
    type: turn_off
  - device_id: f28dc05efd94407e9ec6b17d332fe29b
    domain: light
    entity_id: light.trapp_2
    type: turn_off
  - device_id: b397071e15264940ae3d736547e15896
    domain: light
    entity_id: light.ikea_of_sweden_tradfri_bulb_e27_ww_806lm_f0d83cfe_level_on_off
    type: turn_off
  - device_id: dccd0bc1a092400794e266fb28c3a8d2
    domain: light
    entity_id: light.takterasse_1
    type: turn_off
  - device_id: 69f6c1e792734102b374208260fe84d8
    domain: light
    entity_id: light.takterasse_2
    type: turn_off
- id: '9271295359204'
  alias: Kjøkkenspot dimmer follow
  trigger:
  - entity_id: light.kjokken_spot_1
    platform: state
  action:
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
      entity_id: light.zmnhhdx_mini_dimmer_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1582878880340'
  alias: VVB på
  description: Turning on VVB after 2 hours
  trigger:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    for:
      hours: 2
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    type: turn_on
- id: '1583092645625'
  alias: Gang/hall lys av når entre er lav
  description: ''
  trigger:
  - below: '12'
    entity_id: light.gang_taklampe
    platform: numeric_state
    value_template: '{{ state.attributes.brightness}}'
  condition: []
  action:
  - delay: 00:00:01
  - entity_id: light.hall_spot_1,light.hall_spot_2,light.hall_lampett,light.bod_1,light.bod_2,light.hall_spot_3,light.gangspot_1,light.gangspot_2,light.gangspot_3,light.gangspot_4
    service: light.turn_off
  mode: single
- id: '9271255359204'
  alias: Hallys dimmer follow entre
  trigger:
    platform: state
    entity_id: light.entrelys
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hall_spot_3
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 10 %}\n  11\n{% elif 250 < new_level < 256 %}\n  256\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
- id: '1584820733981'
  alias: Hallys follow entre off
  description: ''
  trigger:
  - entity_id: light.entrelys
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 13d43b5cb130408b9d30a1236be8009a
    domain: light
    entity_id: light.hall_spot_3
    type: turn_off
- id: '1585671607161'
  alias: Pinky Pie Turn on charging
  description: The vacuum cleaner is unable to find the dock if the dock is not powered
    on. This ensures the dock is always on when the vacuum is not docked. Also enables
    charging when battery level is below 60% to maximise battery lifespan.
  trigger:
  - entity_id: sensor.pinky_pie_activity
    from: docked
    platform: state
  - below: '65'
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  condition:
  - below: '85'
    condition: numeric_state
    entity_id: sensor.pinky_pie_battery
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_on
  mode: single
- id: '1585621607161'
  alias: Pinky Pie Turn off when dock
  description: ''
  trigger:
  - entity_id: sensor.pinky_pie_status
    platform: state
    to: docked
  condition:
  - above: '90'
    condition: numeric_state
    entity_id: sensor.pinky_pie_battery
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1585676347188'
  alias: Pinky Pie Turn off when 85%
  description: ''
  trigger:
  - above: '85'
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  condition:
  - condition: state
    entity_id: sensor.pinky_pie_status
    state: docked
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1589619790602'
  alias: Gangspot PÅ
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.gangspot_1
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 4a81fe2588a44c5fb6d548cf11471cc7
    domain: light
    entity_id: light.gangspot_4
    type: turn_on
  mode: single
- id: '1589619816992'
  alias: Gangspot AV
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.gangspot_1
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      entity_id: light.gangspot_4
    service: light.turn_off
  mode: single
- id: '1590345427429'
  alias: Restavfall
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''calendar.soppelhenting_furulien'', ''offset_reached'',true)
      }}'
  condition: []
  action:
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.magnus
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.mona
- id: '1597271290239'
  alias: Badelys på - Natt
  description: ''
  trigger:
  - device_id: ed82ab487127432da58fe62e30e45d03
    domain: light
    entity_id: light.bad_spot_1
    platform: device
    type: turned_on
  condition:
  - after: '23:15:00'
    before: 06:00:00
    condition: time
  action:
  - delay: 00:00:00
  - data:
      brightness_pct: 5
      color_temp: 350
    entity_id: light.badelys
    service: light.turn_on
  mode: single
- id: '1597665827372'
  alias: Gå for dagen
  description: Turns of the house
  trigger:
  - event_data:
      node_id: 16
      scene_id: 2
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - data: {}
    entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.hallys
    - light.bod_1
    - light.bod_2
    service: light.turn_off
  mode: single
- id: '15976657372'
  alias: God natt
  description: Activates night mode for the entire house
  trigger:
  - event_data:
      node_id: 16
      scene_id: 1
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.hall_lampett
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.gang_lampett
    - light.gangspot_1
    - light.gangspot_2
    - light.gangspot_3
    - light.gangspot_4
    - light.bod_1
    - light.bod_2
    service: light.turn_off
  - delay: 00:00:01
  - data:
      transition: 2
      brightness_pct: 5
      color_temp: 350
    entity_id: light.gang_taklampe
    service: light.turn_on
  mode: single
