- alias: Tørketrommel kjører
  trigger:
  - platform: numeric_state
    entity_id: sensor.torketrommel_effekt
    above: '30'
    for:
      seconds: 30
  condition:
    condition: state
    entity_id: input_select.torketrommel
    state: Av
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.torketrommel
      option: Kjører
  id: b20d7866556a4298b33990d207089b9a
- alias: Tørketrommel ferdig
  trigger:
  - platform: numeric_state
    entity_id: sensor.torketrommel_effekt
    below: '7'
    for:
      seconds: 40
  condition:
    condition: state
    entity_id: input_select.torketrommel
    state: Kjører
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.torketrommel
      option: Ferdig
  - service: notify.magnus
    data:
      message: Tørketrommel ferdig
  - service: notify.mona
    data:
      message: Tørketrommel ferdig
  id: 2a0d932475c34ceb89381219aa89190e
- alias: Tørketrommel av
  trigger:
  - platform: state
    entity_id: input_select.torketrommel
    to: Ferdig
    for:
      seconds: 10
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.torketrommel
      option: Av
  id: fa25cc023a0f446485708a1a1368b754
- alias: Vaskemaskin kjører
  trigger:
  - platform: numeric_state
    entity_id: sensor.vaskemaskin_effekt
    above: '20'
    for:
      seconds: 45
  condition:
    condition: state
    entity_id: input_select.vaskemaskin
    state: Av
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.vaskemaskin
      option: Kjører
  id: 912e3b7d42d5421294df2b5d922f6534
- alias: Vaskemaskin ferdig
  trigger:
  - platform: numeric_state
    entity_id: sensor.vaskemaskin_effekt
    below: '2'
    for:
      seconds: 60
  condition:
    condition: state
    entity_id: input_select.vaskemaskin
    state: Kjører
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.vaskemaskin
      option: Ferdig
  - service: notify.magnus
    data:
      message: Vaskemaskin ferdig
  - service: notify.mona
    data:
      message: Vaskemaskin ferdig
  id: 094011b2bab84c4ba826bfe2d291d2e6
- alias: Vaskemaskin av
  trigger:
  - platform: state
    entity_id: input_select.vaskemaskin
    to: Ferdig
    for:
      seconds: 30
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.vaskemaskin
      option: Av
  id: 6b6ae6bb6fcd40518700ef0f572ff60a
- id: '1574633872450'
  alias: Benkelys på
  description: ''
  trigger:
  - entity_id: light.kjokken_spot1
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id:
      - light.benkelys
      - light.qubino_goap_unknown_type_0001_id_0055_level
    service: homeassistant.turn_on
- id: '1574633914308'
  alias: Benkelys av
  description: ''
  trigger:
  - entity_id: light.kjokken_spot1
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id:
      - light.benkelys
      - light.qubino_goap_unknown_type_0001_id_0055_level
    service: homeassistant.turn_off
- id: '1574634050807'
  alias: Gangspot av
  description: ''
  trigger:
  - entity_id: light.hall_entre
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.gangspot
    service: homeassistant.turn_off
- id: '1575139255159'
  alias: Nightly snapshot
  description: ''
  trigger:
  - at: 01:30:00
    platform: time
  condition: []
  action:
  - service: hassio.snapshot_full
- id: '1575295351793'
  alias: Utelys på
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - device_id: e213eb952c0842e0b53232c5fd4a29c9
    domain: light
    entity_id: light.trapp_1
    type: turn_on
  - device_id: b733a2a84a24480c87be546bc5b39faa
    domain: light
    entity_id: light.trapp_2
    type: turn_on
- id: '1575295359193'
  alias: Utelys av
  description: ''
  trigger:
  - event: sunrise
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - device_id: e213eb952c0842e0b53232c5fd4a29c9
    domain: light
    entity_id: light.trapp_1
    type: turn_off
  - device_id: b733a2a84a24480c87be546bc5b39faa
    domain: light
    entity_id: light.trapp_2
    type: turn_off
- id: '1575295359204'
  alias: Completed Torrent
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.magnus
    data_template:
      title: Torrent completed!
      message: '{{trigger.event.data.name}}'
- id: '9271295359204'
  alias: Kjøkkenspot dimmer follow
  trigger:
    platform: state
    entity_id: light.kjokken_spot1
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.qubino_goap_unknown_type_0001_id_0055_level
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
- id: '1576008421024'
  alias: Gangspot on
  description: Automatically turning on Gangspot
  trigger:
  - above: '19'
    entity_id: light.entrelys
    platform: numeric_state
    value_template: '{{ state.attributes.brightness }}'
  condition: []
  action:
  - data: {}
    entity_id: light.gangspot
    service: light.turn_on
- id: '1582878880340'
  alias: VVB på
  description: Turning on VVB after 2 hours
  trigger:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    for:
      hours: 2
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    type: turn_on
- id: '1583088468551'
  alias: Oppvaskmaskin Kjører
  description: ''
  trigger:
  - above: 4
    device_id: ed8ea232992a412ebbd524785b3101a1
    domain: sensor
    entity_id: sensor.oppvaskmaskin_effekt
    for:
      hours: 0
      minutes: 0
      seconds: 30
    platform: device
    type: value
  condition:
  - condition: state
    entity_id: input_select.oppvask
    state: Av
  action:
  - data:
      option: Kjører
    entity_id: input_select.oppvask
    service: input_select.select_option
- id: '1583088738491'
  alias: Oppvaskmaskin Venter
  description: ''
  trigger:
  - above: 19
    below: 35
    device_id: ed8ea232992a412ebbd524785b3101a1
    domain: sensor
    entity_id: sensor.oppvaskmaskin_effekt
    for:
      hours: 0
      minutes: 1
      seconds: 0
    platform: device
    type: value
  condition:
  - condition: state
    entity_id: input_select.oppvask
    state: Kjører
  action:
  - data:
      option: Venter
    entity_id: input_select.oppvask
    service: input_select.select_option
- id: '1583088810262'
  alias: Oppvaskmaskin Tørker
  description: ''
  trigger:
  - above: 500
    device_id: ed8ea232992a412ebbd524785b3101a1
    domain: sensor
    entity_id: sensor.oppvaskmaskin_effekt
    for:
      hours: 0
      minutes: 0
      seconds: 20
    platform: device
    type: value
  condition:
  - condition: state
    entity_id: input_select.oppvask
    state: Venter
  action:
  - data:
      option: Tørker
    service: input_select.select_option
- id: '1583088999060'
  alias: Oppvaskmaskin Ferdig / AV
  description: ''
  trigger:
  - below: 20
    device_id: ed8ea232992a412ebbd524785b3101a1
    domain: sensor
    entity_id: sensor.oppvaskmaskin_effekt
    for:
      hours: 0
      minutes: 0
      seconds: 20
    platform: device
    type: value
  condition:
  - condition: state
    entity_id: input_select.oppvask
    state: Tørker
  action:
  - data:
      option: Ferdig
    entity_id: input_select.oppvask
    service: input_select.select_option
  - delay: 00:00:10
  - data:
      option: Av
    entity_id: input_select.oppvask
    service: input_select.select_option
  - data:
      message: Oppvaskmaskin ferdig
    service: notify.magnus
  - data:
      message: Oppvaskmaskin ferdig
    service: notify.mona
- id: '1583092645625'
  alias: Gang/hall lys av når entre er lav
  description: ''
  trigger:
  - below: '10'
    entity_id: light.entrelys
    platform: numeric_state
    value_template: '{{ state.attributes.brightness}}'
  condition: []
  action:
  - delay: 00:00:02
  - entity_id:
    - light.hall_spot_1
    - light.hall_spot_2
    - light.lampett_2
    - light.bod_1
    - light.bod_2
    - light.hall_spot_3
    - light.skogang_1
    - light.skogang_2
    - light.gangspot
    service: light.turn_off
- id: '1583906335014'
  alias: Lite lagring Synne
  description: ''
  trigger:
  - above: '95'
    entity_id: sensor.synology_dsm_volume_used_volume_1
    for: 00:01:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Mer enn 95% av lagringskapasiteten på Synne er brukt! Slett noe!
    service: notify.magnus
- id: '9271255359204'
  alias: Hallys dimmer follow entre
  trigger:
    platform: state
    entity_id: light.entrelys
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hall_spot_3
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 10 %}\n  11\n{% elif 250 < new_level < 256 %}\n  256\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
- id: '1584820733981'
  alias: Hallys follow entre off
  description: ''
  trigger:
  - entity_id: light.entrelys
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 13d43b5cb130408b9d30a1236be8009a
    domain: light
    entity_id: light.hall_spot_3
    type: turn_off
