- id: '1574633872450'
  alias: Kjøkkenlys på
  description: ''
  trigger:
  - platform: state
    entity_id: light.kjokken_spot_1
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    entity_id: light.julestjerne
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_on
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
    entity_id: light.multilevel_power_switch_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1574633914308'
  alias: Kjøkkenlys av
  description: ''
  trigger:
  - platform: state
    entity_id: light.kjokken_spot_1
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    entity_id: light.julestjerne
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_off
  - device_id: 30d08d4c4a154e94852fa7d6d643bd35
    domain: light
    entity_id: light.multilevel_power_switch_level
    type: turn_off
  mode: parallel
  max: 10
- id: '1575295351793'
  alias: Utelys på
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 220
    entity_id: light.ute
  mode: single
- id: '1575295359193'
  alias: Utelys av
  description: ''
  trigger:
  - event: sunrise
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.ute
  mode: single
- id: '9271295359204'
  alias: Kjøkkenspot dimmer follow
  trigger:
  - entity_id: light.kjokken_spot_1
    platform: state
  action:
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
      entity_id: light.multilevel_power_switch_level
    service: light.turn_on
  mode: restart
  max: 10
- id: '1582878880340'
  alias: VVB på
  description: Turning on VVB after 2 hours
  trigger:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    for:
      hours: 2
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    type: turn_on
- id: '1583092645625'
  alias: Gang/hall lys av når entre er lav
  description: ''
  trigger:
  - below: 12
    entity_id: light.gang_taklampe
    platform: numeric_state
    value_template: '{{ state.attributes.brightness}}'
  condition: []
  action:
  - delay: 00:00:01
  - entity_id: light.hall_spot_1,light.hall_spot_2,light.hall_lampett,light.bod_1,light.bod_2,light.hall_spot_3,light.gangspot_1,light.gangspot_2,light.gangspot_3,light.gangspot_4
    service: light.turn_off
  mode: single
- id: '9271255359204'
  alias: Hallys dimmer follow entre
  trigger:
    platform: state
    entity_id: light.entrelys
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hall_spot_1
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 10 %}\n  11\n{% elif 250 < new_level < 256 %}\n  256\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
- id: '1584820733981'
  alias: Hallys follow entre off
  description: ''
  trigger:
  - entity_id: light.entre
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 13d43b5cb130408b9d30a1236be8009a
    domain: light
    entity_id: light.hall_spot_1
    type: turn_off
- id: '1585671607161'
  alias: Pinky Pie Turn on charging
  description: The vacuum cleaner is unable to find the dock if the dock is not powered
    on. This ensures the dock is always on when the vacuum is not docked. Also enables
    charging when battery level is below 60% to maximise battery lifespan.
  trigger:
  - entity_id: sensor.pinky_pie_activity
    platform: state
    to: Segment cleaning
  - below: 65
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  - entity_id: sensor.pinky_pie_activity
    platform: state
    to: Zoned cleaning
  - entity_id: sensor.pinky_pie_activity
    platform: state
    to: Returning home
  condition: []
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_on
  mode: single
- id: '1585621607161'
  alias: Pinky Pie Turn off when dock
  description: ''
  trigger:
  - entity_id: sensor.pinky_pie_status
    platform: state
    to: docked
  condition:
  - above: 90
    condition: numeric_state
    entity_id: sensor.pinky_pie_battery
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1585676347188'
  alias: Pinky Pie Turn off when 85%
  description: ''
  trigger:
  - above: 85
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  condition:
  - condition: state
    entity_id: sensor.pinky_pie_status
    state: docked
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1589619790602'
  alias: Gangspot PÅ
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.entre
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 4a81fe2588a44c5fb6d548cf11471cc7
    domain: light
    entity_id: light.gangspot
    type: turn_on
  mode: single
- id: '1589619816992'
  alias: Gangspot AV
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.entre
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      entity_id: light.gangspot
    service: light.turn_off
  mode: single
- id: '1590345427429'
  alias: Restavfall
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''calendar.soppelhenting_furulien'', ''offset_reached'',true)
      }}'
  condition: []
  action:
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.magnus
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.mona
- id: '1597271290239'
  alias: Badelys på - Natt
  description: ''
  trigger:
  - device_id: ed82ab487127432da58fe62e30e45d03
    domain: light
    entity_id: light.bad_1
    platform: device
    type: turned_on
  condition:
  - after: '23:15:00'
    before: 06:00:00
    condition: time
  action:
  - delay: 00:00:00
  - data:
      brightness_pct: 5
      color_temp: 350
    entity_id: light.badelys
    service: light.turn_on
  mode: single
- id: '1597665827372'
  alias: Gå for dagen
  description: Turns of the house
  trigger:
  - event_data:
      node_id: 15
      scene_id: 2
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - data: {}
    entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.hallys
    - light.bodlys
    - light.julestjerne
    service: light.turn_off
  mode: single
- id: '15976657372'
  alias: God natt
  description: Activates night mode for the entire house
  trigger:
  - event_data:
      node_id: 15
      scene_id: 1
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.lampett_1
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.lampett_2
    - light.skogang_1
    - light.skogang_2
    - light.skogang_3
    - light.bodlys
    - light.gangspot
    - light.julestjerne
    service: light.turn_off
  - delay: 00:00:01
  - data:
      transition: 2
      brightness_pct: 5
      color_temp: 350
    entity_id: light.entre
    service: light.turn_on
  mode: single
- id: '1600627996392'
  alias: Plantelampe AV
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: light.stue_1
    attribute: brightness
    below: 10
  - platform: device
    type: turned_off
    device_id: e93a7ce237ba41108d619cdaaabc4812
    entity_id: light.stue_1
    domain: light
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.plantelys
  mode: single
- id: '1600628030454'
  alias: Plantelampe på
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: light.stue_1
    attribute: brightness
    above: 15
  - platform: device
    type: turned_on
    device_id: e93a7ce237ba41108d619cdaaabc4812
    entity_id: light.stue_1
    domain: light
  condition: []
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.plantelys
  mode: single
- id: '1771295359204'
  alias: Soveromspot dimmer follow
  trigger:
  - entity_id: light.soverom_1
    platform: state
  action:
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 15 %}\n  65\n{% elif 200 < new_level < 256 %}\n  250\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
      entity_id: light.led_dimmer_z_wave_200w_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1602608287033'
  alias: Soveromspot AV
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: f15480ef0be511ebb84479f1ca5ada15
    entity_id: light.soverom_1
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: 3d9b445f0d7311eb9565438a9471256d
    entity_id: light.led_dimmer_z_wave_200w_level
    domain: light
  mode: single
- id: '1602608326926'
  alias: Soveromspot PÅ
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: f15480ef0be511ebb84479f1ca5ada15
    entity_id: light.soverom_1
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: 3d9b445f0d7311eb9565438a9471256d
    entity_id: light.led_dimmer_z_wave_200w_level
    domain: light
    brightness_pct: 10
  mode: single
- id: '1603134854373'
  alias: Washing Machine - Running
  description: Sets the state of the washing machine to "Running"
  trigger:
  - platform: numeric_state
    entity_id: sensor.vaskemaskin_power
    above: 7
    for: 00:00:15
  condition:
  - condition: state
    entity_id: input_select.washing_machine
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: Running
    entity_id: input_select.washing_machine
  mode: single
- id: '1603135307132'
  alias: Washing Machine - Finished
  description: Setting the state of the washing machine to Finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.vaskemaskin_power
    for: 00:00:20
    below: 8
  condition:
  - condition: state
    entity_id: input_select.washing_machine
    state: Running
  action:
  - service: input_select.select_option
    data:
      option: Finished
    entity_id: input_select.washing_machine
  mode: single
- id: '1603135420151'
  alias: Washing Machine - Off
  description: Setting the state of the washing machine to Off
  trigger:
  - platform: state
    entity_id: input_select.washing_machine
    to: Finished
    for: 00:00:10
  condition: []
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    entity_id: input_select.washing_machine
  mode: single
- id: '1603134854374'
  alias: Dryer - Running
  description: Sets the state of the dryer to "Running"
  trigger:
  - platform: numeric_state
    entity_id: sensor.torketrommel_power
    above: 100
    for: 00:00:20
  condition:
  - condition: state
    entity_id: input_select.dryer
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: Running
    entity_id: input_select.dryer
  mode: single
- id: '1603135307133'
  alias: Dryer - Finished
  description: Setting the state of the dryer to Finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.torketrommel_power
    below: 5
    for: 00:00:30
  condition:
  - condition: state
    entity_id: input_select.dryer
    state: Running
  action:
  - service: input_select.select_option
    data:
      option: Finished
    entity_id: input_select.dryer
  mode: single
- id: '1603135420152'
  alias: Dryer - Off
  description: Setting the state of the dryer to Off
  trigger:
  - platform: state
    entity_id: input_select.dryer
    to: Finished
    for: 00:00:10
  condition: []
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    entity_id: input_select.dryer
  mode: single
- id: '7803139396910'
  alias: Notify when washing machine finishes
  trigger:
  - platform: state
    entity_id: input_select.washing_machine
    to: Finished
  condition: []
  action:
  - service: notify.mobile_app_magnuss_iphone
    data:
      message: Vaskemaskinen er ferdig!
  - service: notify.mobile_app_monas_iphone
    data:
      message: Vaskemaskinen er ferdig!
  mode: single
- id: '7803102396910'
  alias: Notify when tumble dryer machine finishes
  trigger:
  - platform: state
    entity_id: input_select.dryer
    to: Finished
  condition: []
  action:
  - service: notify.mobile_app_magnuss_iphone
    data:
      message: Tørketrommelen er ferdig!
  - service: notify.mobile_app_monas_iphone
    data:
      message: Tørketrommelen er ferdig!
  mode: single
- id: '1603787677901'
  alias: Dish Washer - Finished
  description: Setting the state of the dish washer to Finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.oppvaskmaskin_effekt
    for: 00:01:00
    below: 5
  condition:
  - condition: state
    entity_id: input_select.dish_washer
    state: Running
  action:
  - service: input_select.select_option
    data:
      option: Finished
    entity_id: input_select.dish_washer
  mode: single
- id: '1603787715889'
  alias: Dish Washer - Off
  description: Setting the state of the dish washer to Off
  trigger:
  - platform: state
    entity_id: input_select.dish_washer
    to: Finished
    for: 00:00:10
  condition: []
  action:
  - service: input_select.select_option
    data:
      option: 'Off'
    entity_id: input_select.dish_washer
  mode: single
- id: '1603787767278'
  alias: Dish Washer - Running
  description: Sets the state of the dish washer to "Running"
  trigger:
  - platform: numeric_state
    entity_id: sensor.oppvaskmaskin_effekt
    above: 7
    for: 00:00:15
  condition:
  - condition: state
    entity_id: input_select.dish_washer
    state: 'Off'
  action:
  - service: input_select.select_option
    data:
      option: Running
    entity_id: input_select.dish_washer
  mode: single
- id: '2497665127372'
  alias: Komme hjem
  description: Turns on hallys, kjøkken and stue
  trigger:
  - event_data:
      node_id: 15
      scene_id: 3
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - data: {}
    entity_id:
    - light.kjokkenlys
    - light.stuelys
    - light.hallys
    - light.bodlys
    - light.julestjerne
    service: light.turn_on
  mode: single
- id: '2497665937372'
  alias: Toggle utelys
  description: Turns on/off utelys
  trigger:
  - event_data:
      node_id: 15
      scene_id: 4
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.utelys
  - delay:
      seconds: 2
  mode: single
- id: '1606207303612'
  alias: Notify if garage door is open at night
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: state
    entity_id: cover.garage_door
    state: open
  action:
  - service: notify.mobile_app_magnuss_iphone
    data:
      message: Garasjedøren er åpen
  - service: notify.mobile_app_monas_iphone
    data:
      message: Garasjedøren er åpen
  mode: single
