- id: '1571509382427'
  alias: Create Snapshot
  description: ''
  trigger:
  - at: 05:00:00
    platform: time
  condition: []
  action:
  - data:
    service: hassio.snapshot_full
    data_template:
      name: Hassio ({{now().strftime('%d.%m.%y')}})
