- id: '1574633872450'
  alias: Kjøkkenlys på
  description: ''
  trigger:
  - device_id: 0195134ee8c64a448e7de244abfdd687
    domain: light
    entity_id: light.kjokken_spot_1
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_on
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
    entity_id: light.zmnhhdx_mini_dimmer_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1574633914308'
  alias: Kjøkkenlys av
  description: ''
  trigger:
  - device_id: 0195134ee8c64a448e7de244abfdd687
    domain: light
    entity_id: light.kjokken_spot_1
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: 67675efd53a74c9795e1c5f667db2c68
    domain: light
    entity_id: light.benkelys
    type: turn_off
  - device_id: 30d08d4c4a154e94852fa7d6d643bd35
    domain: light
    entity_id: light.zmnhhdx_mini_dimmer_level
    type: turn_off
  mode: parallel
  max: 10
- id: '1575295351793'
  alias: Utelys på
  description: ''
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
  condition: []
  action:
  - type: turn_on
    device_id: 4014de3158de47e0b81d1d382d3e4e89
    entity_id: light.trapp_1
    domain: light
    brightness_pct: 90
  - type: turn_on
    device_id: 1ad92334644e4834a17d8aa0adff913b
    entity_id: light.trapp_2
    domain: light
    brightness_pct: 90
  - type: turn_on
    device_id: 737439b3fb3e11eab9f9775f85fbdfe0
    entity_id: light.garasje_forran
    domain: light
    brightness_pct: 90
  - type: turn_on
    device_id: 73745538fb3e11eaa421395a6c6c39d6
    entity_id: light.garasje_side
    domain: light
    brightness_pct: 90
  mode: single
- id: '1575295359193'
  alias: Utelys av
  description: ''
  trigger:
  - event: sunrise
    offset: 00:45:00
    platform: sun
  condition: []
  action:
  - type: turn_off
    device_id: 4014de3158de47e0b81d1d382d3e4e89
    entity_id: light.trapp_1
    domain: light
  - type: turn_off
    device_id: 1ad92334644e4834a17d8aa0adff913b
    entity_id: light.trapp_2
    domain: light
  - type: turn_off
    device_id: 737439b3fb3e11eab9f9775f85fbdfe0
    entity_id: light.garasje_forran
    domain: light
  - type: turn_off
    device_id: 73745538fb3e11eaa421395a6c6c39d6
    entity_id: light.garasje_side
    domain: light
  mode: single
- id: '9271295359204'
  alias: Kjøkkenspot dimmer follow
  trigger:
  - entity_id: light.kjokken_spot_1
    platform: state
  action:
  - data_template:
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 55 %}\n  65\n{% elif 200 < new_level < 256 %}\n  160\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
      entity_id: light.zmnhhdx_mini_dimmer_level
    service: light.turn_on
  mode: parallel
  max: 10
- id: '1582878880340'
  alias: VVB på
  description: Turning on VVB after 2 hours
  trigger:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    for:
      hours: 2
      minutes: 0
      seconds: 0
    platform: device
    type: turned_off
  condition: []
  action:
  - device_id: c12d8b46a49f497d8cabbd9b8bf3d304
    domain: switch
    entity_id: switch.varmtvannsbereder
    type: turn_on
- id: '1583092645625'
  alias: Gang/hall lys av når entre er lav
  description: ''
  trigger:
  - below: 12
    entity_id: light.gang_taklampe
    platform: numeric_state
    value_template: '{{ state.attributes.brightness}}'
  condition: []
  action:
  - delay: 00:00:01
  - entity_id: light.hall_spot_1,light.hall_spot_2,light.hall_lampett,light.bod_1,light.bod_2,light.hall_spot_3,light.gangspot_1,light.gangspot_2,light.gangspot_3,light.gangspot_4
    service: light.turn_off
  mode: single
- id: '9271255359204'
  alias: Hallys dimmer follow entre
  trigger:
    platform: state
    entity_id: light.entrelys
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.hall_spot_3
      brightness: "{% set new_level = trigger.to_state.attributes.brightness|int %}\
        \ {% if 0 < new_level < 10 %}\n  11\n{% elif 250 < new_level < 256 %}\n  256\n\
        {% else %}\n  {{ new_level }}\n{% endif %}"
- id: '1584820733981'
  alias: Hallys follow entre off
  description: ''
  trigger:
  - entity_id: light.entrelys
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 13d43b5cb130408b9d30a1236be8009a
    domain: light
    entity_id: light.hall_spot_3
    type: turn_off
- id: '1585671607161'
  alias: Pinky Pie Turn on charging
  description: The vacuum cleaner is unable to find the dock if the dock is not powered
    on. This ensures the dock is always on when the vacuum is not docked. Also enables
    charging when battery level is below 60% to maximise battery lifespan.
  trigger:
  - entity_id: sensor.pinky_pie_activity
    platform: state
    to: cleaning
  - below: 65
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  condition: []
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_on
  mode: single
- id: '1585621607161'
  alias: Pinky Pie Turn off when dock
  description: ''
  trigger:
  - entity_id: sensor.pinky_pie_status
    platform: state
    to: docked
  condition:
  - above: '90'
    condition: numeric_state
    entity_id: sensor.pinky_pie_battery
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1585676347188'
  alias: Pinky Pie Turn off when 85%
  description: ''
  trigger:
  - above: 85
    entity_id: sensor.pinky_pie_battery
    platform: numeric_state
  condition:
  - condition: state
    entity_id: sensor.pinky_pie_status
    state: docked
  action:
  - device_id: 596c9d618738444cb6a7cf4a8cdc4fab
    domain: switch
    entity_id: switch.pinky_pie_plug_switch
    type: turn_off
  mode: single
- id: '1589619790602'
  alias: Gangspot PÅ
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.gangspot_1
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: 4a81fe2588a44c5fb6d548cf11471cc7
    domain: light
    entity_id: light.gangspot_4
    type: turn_on
  mode: single
- id: '1589619816992'
  alias: Gangspot AV
  description: ''
  trigger:
  - device_id: 391e75dcf20e40b881fb9a0a7f7b9a2d
    domain: light
    entity_id: light.gangspot_1
    platform: device
    type: turned_off
  condition: []
  action:
  - data:
      entity_id: light.gangspot_4
    service: light.turn_off
  mode: single
- id: '1590345427429'
  alias: Restavfall
  description: ''
  trigger:
  - platform: template
    value_template: '{{ is_state_attr(''calendar.soppelhenting_furulien'', ''offset_reached'',true)
      }}'
  condition: []
  action:
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.magnus
  - data:
      message: '{{ state_attr(''calendar.soppelhenting_furulien'', ''message'')}}
        i morgen tidlig!'
    service: notify.mona
- id: '1597271290239'
  alias: Badelys på - Natt
  description: ''
  trigger:
  - device_id: ed82ab487127432da58fe62e30e45d03
    domain: light
    entity_id: light.bad_spot_1
    platform: device
    type: turned_on
  condition:
  - after: '23:15:00'
    before: 06:00:00
    condition: time
  action:
  - delay: 00:00:00
  - data:
      brightness_pct: 5
      color_temp: 350
    entity_id: light.badelys
    service: light.turn_on
  mode: single
- id: '1597665827372'
  alias: Gå for dagen
  description: Turns of the house
  trigger:
  - event_data:
      node_id: 16
      scene_id: 2
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - data: {}
    entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.hallys
    - light.bod_1
    - light.bod_2
    service: light.turn_off
  mode: single
- id: '15976657372'
  alias: God natt
  description: Activates night mode for the entire house
  trigger:
  - event_data:
      node_id: 16
      scene_id: 1
    event_type: ozw.scene_activated
    platform: event
  condition: []
  action:
  - entity_id:
    - light.badelys
    - light.kjokkenlys
    - light.stuelys
    - light.hall_lampett
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.gang_lampett
    - light.gangspot_1
    - light.gangspot_2
    - light.gangspot_3
    - light.gangspot_4
    - light.bod_1
    - light.bod_2
    service: light.turn_off
  - delay: 00:00:01
  - data:
      transition: 2
      brightness_pct: 5
      color_temp: 350
    entity_id: light.gang_taklampe
    service: light.turn_on
  mode: single
- id: '1600102402259'
  alias: Tag - Toggle living room light
  description: ''
  trigger:
  - platform: tag
    tag_id: A0-FE-DE-A4
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.stuelys
  mode: single
- id: '1600117484045'
  alias: Tag ToggleTag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: A0-FE-DE-A4
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.stuelys
  mode: single
- id: '1600117703126'
  alias: ESPhome Tagreader - Toggle living room lights
  description: ''
  trigger:
  - platform: tag
    tag_id: A0-FE-DE-A4
  condition: []
  action:
  - service: light.toggle
    data: {}
    entity_id: light.stuelys
  mode: single
- id: '1600627996392'
  alias: Plantelampe AV
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: light.stue_spot_1
    attribute: brightness
    below: '10'
  - platform: device
    type: turned_off
    device_id: e93a7ce237ba41108d619cdaaabc4812
    entity_id: light.stue_spot_1
    domain: light
  condition: []
  action:
  - type: turn_off
    device_id: f114c75ffb7111ea80dfd56621ee68ae
    entity_id: switch.stue_taklampe_switch_2
    domain: switch
  mode: single
- id: '1600628030454'
  alias: Plantelampe på
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: light.stue_spot_1
    attribute: brightness
    above: '15'
  - platform: device
    type: turned_on
    device_id: e93a7ce237ba41108d619cdaaabc4812
    entity_id: light.stue_spot_1
    domain: light
  condition: []
  action:
  - type: turn_on
    device_id: f114c75ffb7111ea80dfd56621ee68ae
    entity_id: switch.stue_taklampe_switch_2
    domain: switch
  mode: single
