api:
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
cloud:
config:
cover: !include cover.yaml
duckdns: !include duckdns.yaml
discovery:
esphome_tag:
frontend:
google:
  client_id: !secret google_id
  client_secret: !secret google_secret
group: !include groups.yaml
#hacs: !include hacs.yaml
history:
http: !include http.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
input_text: !include input_text.yaml
ios: !include ios.yaml
light: !include light.yaml
logbook:
logger:
  logs:
    homeassistant.components.songpal: error
    homeassistant.components.mqtt: error
    homeassistant.loader: error
map:
media_player: !include media_player.yaml
mobile_app:
notify: !include notify.yaml
#octoprint: !include octoprint.yaml
panel_iframe: !include panel_iframe.yaml
person:
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
ssdp:
system_health:
sun:
telegram_bot: !include telegram_bot.yaml
tibber: !include tibber.yaml
utility_meter: !include utility_meter.yaml
updater:
vacuum: !include vacuum.yaml
volkswagencarnet: !include carnet.yaml
zeroconf:
zone: !include zone.yaml