automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
default_config:
frontend:
group: !include groups.yaml
hacs: !include hacs.yaml
http: !include http.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
light: !include light.yaml
logger:
media_player: !include media_player.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
system_health:
telegram_bot: !include telegram_bot.yaml
tibber: !include tibber.yaml
unifi: !include unifi.yaml
utility_meter: !include utility_meter.yaml
volkswagencarnet: !include carnet.yaml
