automation: !include automations.yaml
automation split: !include_dir_merge_list automation/
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
default_config:
frontend:
  themes: !include themes.yaml
group: !include groups.yaml
hacs: !include hacs.yaml
http: !include http.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
system_health:
telegram_bot: !include telegram_bot.yaml
tibber: !include tibber.yaml
unifi: !include unifi.yaml
utility_meter: !include utility_meter.yaml
#volkswagencarnet:
#  username: !secret gte_username
#  password: !secret gte_password
#  scan_interval:
#    minutes: 2
#  name:
#    wvwzzz3czle033777: 'Passat GTE'
volkswagencarnet:
    username: !secret gte_username
    password: !secret gte_password
    scan_interval: 
        minutes: 2
    name:
        WVWZZZ3CZLE033777: 'Passat GTE'