automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
climate: !include climate.yaml
cloud:
config:
cover: !include cover.yaml
duckdns: !include duckdns.yaml
discovery:
  ignore:
    - igd
    - upnp
frontend:
group: !include groups.yaml
hacs: !include hacs.yaml
history:
http: !include http.yaml
influxdb: !include influxdb.yaml
input_select: !include input_select.yaml
light: !include light.yaml
logbook:
logger:
  default: info
map:
media_player: !include media_player.yaml
mobile_app:
notify: !include notify.yaml
octoprint: !include octoprint.yaml
panel_iframe: !include panel_iframe.yaml
person:
recorder: !include recorder.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
ssdp:
system_health:
sun:
telegram_bot: !include telegram_bot.yaml
tibber: !include tibber.yaml
utility_meter: !include utility_meter.yaml
updater:
vacuum: !include vacuum.yaml
volkswagencarnet: !include carnet.yaml
zeroconf:
zone: !include zone.yaml