- platform: template
  covers:
    garage_door:
      friendly_name: Garasjeport
      device_class: garage
      close_cover:
        service: switch.toggle
        data:
          entity_id: switch.zmnhnd1_flush_1d_relay_switch
      open_cover:
        service: switch.toggle
        data:
          entity_id: switch.zmnhnd1_flush_1d_relay_switch
      value_template: >-
        {% if is_state('binary_sensor.notification_sensor_access_control_door_window_open', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.notification_sensor_access_control_door_window_open', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}