- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      open_cover:
        service: script.garage_door_trigger
      close_cover:
        service: script.garage_door_trigger
      value_template: >-
        {% if is_state('binary_sensor.openclose_9', 'on') %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.openclose_9', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}