- platform: template
  covers:
    garage_door:
      device_class: garage
      friendly_name: "Garage Door"
      open_cover:
        service: script.garage_door_trigger
      close_cover:
        service: script.garage_door_trigger
      value_template: "{{ is_state('binary_sensor.fgk10x_door_opening_sensor_sensor', 'on') }}"
      icon_template: >-
        {% if is_state('binary_sensor.fgk10x_door_opening_sensor_sensor', 'on') %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}