- platform: template
  covers:
    garage_door:
      friendly_name: Garasjeport
      device_class: garage
      close_cover:
        service: switch.toggle
        data:
          entity_id: switch.binary_power_switch_switch
      open_cover:
        service: switch.toggle
        data:
          entity_id: switch.binary_power_switch_switch
      value_template: >-
        {% if is_state("binary_sensor.fgk10x_door_opening_sensor_access_control_door_window_open", "Closed") %}
          Closed
        {% else %}
          Open
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.fgk10x_door_opening_sensor_access_control_door_window_open", "Closed") %}
          mdi:garage
        {% else %}
          mdi:garage-open
        {% endif %}