- platform: template
  covers:
    garage_door:
      friendly_name: Garasjeport
      device_class: garage
      close_cover:
        service: switch.toggle
        data:
          entity_id: switch.qubino_goap_zmnhnd1_flush_1d_relay_switch
      open_cover:
        service: switch.toggle
        data:
          entity_id: switch.qubino_goap_zmnhnd1_flush_1d_relay_switch
      value_template: >-
        {% if is_state("binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor", "off") %}
          Open
        {% else %}
          Closed
        {% endif %}
      icon_template: >-
        {% if is_state("binary_sensor.fibaro_system_fgk10x_door_opening_sensor_sensor", "off") %}
          mdi:garage-open
        {% else %}
          mdi:garage
        {% endif %}