- platform: group
  name: Kjøkkenlys
  entities:
    - light.kjokken_spot_1
    - light.kjokken_spot_2
    - light.kjokken_spot_3
    - light.benkelys
    - light.zmnhhdx_mini_dimmer_level
- platform: group
  name: Hallys
  entities:
    - light.hall_lampett
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.gangspot_1
    - light.gangspot_2
    - light.gangspot_3
    - light.gangspot_4
    - light.gang_lampett
    - light.gang_taklampe
- platform: group
  name: Stuelys
  entities:
    - light.stue_sofabord
    - light.stue_spot_1
    - light.stue_spot_2
    - light.stue_spot_3
    - light.stue_taklampe