- platform: group
  name: Kjøkkenlys
  entities:
    - light.kjokken_spot_1
    - light.kjokken_spot_2
    - light.kjokken_spot_3
    - light.ventilator_1
    - light.ventilator_2
    - light.benkelys
    - light.zmnhhdx_mini_dimmer_level
- platform: group
  name: Hallys
  entities:
    - light.hall_lampett
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.gangspot_1
    - light.gangspot_2
    - light.gangspot_3
    - light.gangspot_4
    - light.gang_lampett
    - light.gang_taklampe
- platform: group
  name: Stuelys
  entities:
    - light.stue_sofabord
    - light.stue_spot_1
    - light.stue_spot_2
    - light.stue_spot_3
    - light.stue_taklampe
- platform: group
  name: Badelys
  entities:
    - light.bad_speil
    - light.bad_spot_1
    - light.bad_spot_2
    - light.bad_spot_3
    - light.bad_spot_4
    - light.bad_spot_5
- platform: group
  name: Soveromlys
  entities:
    - light.soverom_spot_1
    - light.soverom_spot_2
    - light.soverom_spot_3
- platform: group
  name: Bodlys
  entities:
    - light.bod_1
    - light.bod_2
- platform: group
  name: Utelys
  entities:
    - light.trapp_1
    - light.trapp_2
    - light.garasje_forran
    - light.garasje_side
- platform: template
  lights:
    plantelys:
      friendly_name: "Plantelys"
      turn_on:
        service: switch.turn_on
        entity_id: switch.zw139_nano_switch_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.zw139_nano_switch_switch
      value_template: >-
        {% if is_state('switch.zw139_nano_switch_switch', 'on') %}
          on
        {% elif is_state('switch.zw139_nano_switch_switch', 'off') %}
          off
        {% else %}
          unknown
        {% endif %}