- platform: group
  name: Kjøkkenlys
  entities:
    - light.kjokken_spot_1
    - light.kjokken_spot_2
    - light.kjokken_spot_3
    - light.ventilator_1
    - light.ventilator_2
    - light.benkelys
    - light.zmnhhdx_mini_dimmer_level
- platform: group
  name: Hallys
  entities:
    - light.lampett_1
    - light.lampett_2
    - light.hall_spot_1
    - light.hall_spot_2
    - light.hall_spot_3
    - light.skogang_1
    - light.skogang_2
    - light.skogang_3
    - light.gangspot
    - light.entre
- platform: group
  name: Stuelys
  entities:
    - light.stue_1
    - light.stue_2
    - light.stue_3
    - light.stue_4

- platform: group
  name: Badelys
  entities:
    - light.bad_speil
    - light.bad_1
    - light.bad_2
    - light.bad_3
    - light.bad_4
    - light.bad_5
- platform: group
  name: Soveromlys
  entities:
    - light.soverom_1
    - light.soverom_2
    - light.soverom_3
- platform: group
  name: Bodlys
  entities:
    - light.bod_1
    - light.bod_2
- platform: group
  name: Utelys
  entities:
    - light.ute_1
    - light.ute_2
    - light.garage_1
    - light.garage_2
- platform: template
  lights:
    plantelys:
      friendly_name: "Plantelys"
      turn_on:
        service: switch.turn_on
        entity_id: switch.zw139_nano_switch_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.zw139_nano_switch_switch
      value_template: >-
        {% if is_state('switch.zw139_nano_switch_switch', 'on') %}
          on
        {% else %}
          off
        {% endif %}
    julestjerne:
      friendly_name: "Julestjerne"
      turn_on:
        service: switch.turn_on
        entity_id: "switch.zw096_smart_switch_6_switch"
      turn_off:
        service: switch.turn_off
        entity_id: "switch.zw096_smart_switch_6_switch"
