- platform: songpal
  name: STR-DN1080_Receiever
  endpoint: http://192.168.1.58:10000/sony
- platform: samsungtv
  host: 192.168.1.229
  name: Q9FN
  mac: fc:03:9f:7c:a4:26
  port: 8002
- platform: spotify
  client_id: a935d732cda447f0989d2b2b6f72502e
  client_secret: 97033bf5cfd24e7a9b0ab477579ef129
- platform: androidtv
  host: 192.168.1.78
  name: "NVidia Shield"
  adb_server_ip: 127.0.0.1
  adb_server_port: 5037