- platform: songpal
  name: STR-DN1080_Receiever
  endpoint: http://192.168.1.58:10000/sony
- platform: samsungtv_custom
  host: 192.168.1.229
  name: Q9FN
  port: 8002
  mac: fc:03:9f:7c:a4:26
  sourcelist: '{"STR-DN1080": "KEY_HDMI1"}'
  applist: "YouTube, Plex, Spotify"
  protocol: ws