- platform: template
  sensors:
## TIBBER ##
    electricity_price_furulien_18_percent:
      friendly_name: "Strømpris %"
      unit_of_measurement: '%'
      value_template: >-
        {% set max = states.sensor.electricity_price_furulien_18.attributes.max_price | float %}
        {% set cur = states.sensor.electricity_price_furulien_18.state | float %}
        {% set min = states.sensor.electricity_price_furulien_18.attributes.min_price | float %}
          {{ ((cur - min) / ((max - min) / 100)) | round(0)}}
    electricity_price_furulien_18_daily_usage:
      friendly_name: Dagforbruk
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') }}"

## ANDEL ##
    av_andel:
      friendly_name: "AV Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.av_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    it_andel:
      friendly_name: "IT Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.it_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmtvannsbereder_andel:
      friendly_name: "Varmtvannsbereder Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmtvannsbereder_daily_energy_2') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    torketrommel_andel:
      friendly_name: "Tørketrommel Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.torketrommel_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    vaskemaskin_andel:
      friendly_name: "Vaskemaskin Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.vaskemaskin_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    komfyr_andel:
      friendly_name: "Komfyr Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.komfyr_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    oppvaskmaskin_andel:
      friendly_name: "Oppvaskmaskin Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.oppvaskmaskin_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    panelovn_stue_andel:
      friendly_name: "Panelovn Stue Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.panelovn_stue_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    panelovn_gjesterom_andel:
      friendly_name: "Gjesterom Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.panelovn_gjesterom_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    vifteovn_andel:
      friendly_name: "Vifteovn Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.vifteovn_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    fryser_andel:
      friendly_name: "Fryser Andel"
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.fryser_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    kjoleskap_andel:
      friendly_name: "Kjøleskap Andel"
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.kjoleskap_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmekabler_bad_andel:
      friendly_name: "Varmekabler Bad Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmekabler_bad_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmekabler_barnerom_andel:
      friendly_name: "Varmekabler Barnerom Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmekabler_barnerom_daily') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    gangspot_andel:
      friendly_name: "Gangspot Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.gangspot_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    kaffetrakter_andel:
      friendly_name: "Kaffetrakter Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.kaffetrakter_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    pinkypie_andel:
      friendly_name: "Pinky Pie Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.pinky_pie_plug_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    gte_andel:
      friendly_name: "Gangspot Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.gte_ladeplugg_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    restforbruk:
      friendly_name: 'Rest'
      unit_of_measurement: '%'
      value_template: "{{ 100 - ( (states('sensor.gangspot_andel') | float) + (states('sensor.it_andel') | float) + (states('sensor.av_andel') | float) + (states('sensor.varmekabler_bad_andel') | float) + (states('sensor.komfyr_andel') | float ) + (states('sensor.oppvaskmaskin_andel') | float ) + (states('sensor.panelovn_stue_andel') | float ) + (states('sensor.torketrommel_andel') | float ) + (states('sensor.varmtvannsbereder_andel') | float ) + (states('sensor.vaskemaskin_andel') | float ) + (states('sensor.panelovn_gjesterom_andel') | float ) + (states('sensor.kjoleskap_andel') | float) + (states('sensor.fryser_andel') | float) + (states('sensor.varmekabler_barnerom_andel') | float) + (states('sensor.vifteovn_andel') | float) | round(2) + (states('sensor.gte_andel') | float) | round(2)) }}"

## XIAOMI VACUUM ##
    pinky_pie_battery:
      friendly_name: 'Pinky Pie Battery'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('vacuum.pinky_pie', 'battery_level') }}"

    pinky_pie_activity:
      friendly_name: 'Pinky Pie Status'
      value_template: "{{ state_attr('vacuum.pinky_pie', 'status') }}"

    pinky_pie_status:
      friendly_name: 'Pinky Pie Status'
      value_template: "{{ states('vacuum.pinky_pie') }}"

##################
#  REST-sensors ##
##################

#MARIADB
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/core_mariadb/info
  name: MariaDB status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#ADGUARD
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_adguard/info
  name: AdGuard status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#ESPhome
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_esphome/info
  name: ESPhome status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state

#Glances
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_glances/info
  name: Galnces status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#Grafana
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_grafana/info
  name: Grafana status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#Google Drive Backup
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/cebe7a76_hassio_google_drive_backup/info
  name: GoogleDrive status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#InfluxDB
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_influxdb/info
  name: InfluxDB status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#MQTT Broker
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/core_mosquitto/info
  name: MQTTbroker status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#NGINX
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_nginxproxymanager/info
  name: Nginx status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#Node-RED
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_nodered/info
  name: Node-RED status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 10
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#OZW
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/core_zwave/info
  name: OpenZwave status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 20
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#SAMBA
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/core_samba/info
  name: Samba status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 20
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name

#SVSCode
- platform: rest
  resource: http://192.168.1.35:8123/api/hassio/addons/a0d7b954_vscode/info
  name: VSCode status
  method: GET
  value_template: '{{ value_json.data.state }}'
  scan_interval: 20
  headers:
    Authorization: !secret llt
    Content-Type: application/json
  json_attributes_path: "$.data"
  json_attributes:
    - state
    - name