- platform: template
  sensors:
## TIBBER ##
    electricity_price_furulien_18_percent:
      friendly_name: "Strømpris %"
      unit_of_measurement: '%'
      value_template: >-
        {% set max = states.sensor.electricity_price_furulien_18.attributes.max_price | float %}
        {% set cur = states.sensor.electricity_price_furulien_18.state | float %}
        {% set min = states.sensor.electricity_price_furulien_18.attributes.min_price | float %}
          {{ ((cur - min) / ((max - min) / 100)) | round(0)}}
    electricity_price_furulien_18_daily_usage:
      friendly_name: Dagforbruk
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') }}"

## ANDEL ##
    av_andel:
      friendly_name: "AV Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.av_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    it_andel:
      friendly_name: "IT Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.it_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmtvannsbereder_andel:
      friendly_name: "Varmtvannsbereder Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmtvannsbereder_daily_energy_2') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    torketrommel_andel:
      friendly_name: "Tørketrommel Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.torketrommel_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    vaskemaskin_andel:
      friendly_name: "Vaskemaskin Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.vaskemaskin_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    komfyr_andel:
      friendly_name: "Komfyr Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.komfyr_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    oppvaskmaskin_andel:
      friendly_name: "Oppvaskmaskin Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.oppvaskmaskin_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    panelovn_stue_andel:
      friendly_name: "Panelovn Stue Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.panelovn_stue_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    panelovn_gjesterom_andel:
      friendly_name: "Gjesterom Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.panelovn_gjesterom_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    vifteovn_andel:
      friendly_name: "Vifteovn Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.vifteovn_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    fryser_andel:
      friendly_name: "Fryser Andel"
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.fryser_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    kjoleskap_andel:
      friendly_name: "Kjøleskap Andel"
      unit_of_measurement: "%"
      value_template: "{{ ((states('sensor.kjoleskap_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmekabler_bad_andel:
      friendly_name: "Varmekabler Bad Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmekabler_bad_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmekabler_barnerom_andel:
      friendly_name: "Varmekabler Barnerom Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.varmekabler_barnerom_daily') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    varmekabler_barnerom_til_kw:
      friendly_name: "Varmekabler Barnerom kW"
      unit_of_measurement: 'kwh'
      value_template: "{{ ((states('sensor.heatit_thermostat_tf_058_electric_w') | float / 1000) | round(3)) }}"

    gangspot_andel:
      friendly_name: "Gangspot Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.gangspot_dagsforbruk') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    kaffetrakter_andel:
      friendly_name: "Kaffetrakter Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.kaffetrakter_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    pinkypie_andel:
      friendly_name: "Pinky Pie Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.pinky_pie_plug_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    gte_andel:
      friendly_name: "Gangspot Andel"
      unit_of_measurement: '%'
      value_template: "{{ ((states('sensor.gte_ladeplugg_daily_energy') | float / state_attr('sensor.real_time_consumption_furulien_18', 'accumulatedConsumption') | float) * 100) | round(2) }}"

    restforbruk:
      friendly_name: 'Rest'
      unit_of_measurement: '%'
      value_template: "{{ 100 - ( (states('sensor.gangspot_andel') | float) + (states('sensor.it_andel') | float) + (states('sensor.av_andel') | float) + (states('sensor.varmekabler_bad_andel') | float) + (states('sensor.komfyr_andel') | float ) + (states('sensor.oppvaskmaskin_andel') | float ) + (states('sensor.panelovn_stue_andel') | float ) + (states('sensor.torketrommel_andel') | float ) + (states('sensor.varmtvannsbereder_andel') | float ) + (states('sensor.vaskemaskin_andel') | float ) + (states('sensor.panelovn_gjesterom_andel') | float ) + (states('sensor.kjoleskap_andel') | float) + (states('sensor.fryser_andel') | float) + (states('sensor.varmekabler_barnerom_andel') | float) + (states('sensor.vifteovn_andel') | float) | round(2) + (states('sensor.gte_andel') | float) | round(2)) }}"

## XIAOMI VACUUM ##
    pinky_pie_battery:
      friendly_name: 'Pinky Pie Battery'
      unit_of_measurement: '%'
      value_template: "{{ state_attr('vacuum.pinky_pie', 'battery_level') }}"

    pinky_pie_activity:
      friendly_name: 'Pinky Pie Status'
      value_template: "{{ state_attr('vacuum.pinky_pie', 'status') }}"

    pinky_pie_status:
      friendly_name: 'Pinky Pie Status'
      value_template: "{{ states('vacuum.pinky_pie') }}"