#- platform: broadcast
#  api_key: !secret telegram_api
#  allowed_chat_ids:
#    - !secret telegram_chat_magnus
#    - !secret telegram_chat_mona
- platform: polling
  api_key: !secret telegram_api
  allowed_chat_ids:
    - !secret telegram_chat_magnus
    - !secret telegram_chat_mona