- alias: 'Gå for dagen'
  trigger:
  - event_data:
      scene_id: 2
      node_id: 7
    event_type: zwave.scene_activated
    platform: event
  action:
    service: light.turn_off
    entity_id:
      - light.stue_salong
      - light.stue_spisebord
      - light.stue_spot_1
      - light.stue_spot_2
      - light.stue_spot_3
      - light.bad_1_2
      - light.bad_2_2
      - light.bad_3_2
      - light.bad_4_2
      - light.bad_5_2
      - light.bad_speil_2
      - light.entrelys
      - light.bod
      - light.kjokken_1_2
      - light.kjokken_2_2
      - light.kjokken_3_2
      - light.kjokkenspot
      - light.ventilator_1
      - light.ventilator_2
      - light.benkelys
      - light.hall_1_2
      - light.hall_2_2
      - light.hall_4_2
      - light.hall_5_2
      - light.hall_6
      - light.skogang_1_2
      - light.skogang_2_2
      - light.skogang_3_2
      - light.entre_2
- alias: 'God natt'
  trigger:
  - event_data:
      scene_id: 1
      node_id: 7
    event_type: zwave.scene_activated
    platform: event
  action:
    - service: homeassistant.turn_off
      entity_id:
        - light.stue_salong
        - light.stue_spisebord
        - light.stue_spot_1
        - light.stue_spot_2
        - light.stue_spot_3
        - light.kjokken_1_2
        - light.kjokken_2_2
        - light.kjokken_3_2
        - light.kjokkenspot
        - light.ventilator_1
        - light.ventilator_2
        - light.benkelys
        - light.bad_1_2
        - light.bad_2_2
        - light.bad_3_2
        - light.bad_4_2
        - light.bad_5_2
        - light.bad_speil_2
        - light.bod
        - light.hall_1_2
        - light.hall_4_2
        - light.hall_5_2
        - light.hall_6
        - light.skogang_1_2
        - light.skogang_2_2
        - light.skogang_3_2
    - service: light.turn_on
      data:
        brightness_pct: 1
        entity_id:
          - light.hall_2_2
          - light.entre_2
- id: '1571509382427'
  alias: Create Snapshot
  description: ''
  trigger:
  - at: 00:00:00
    platform: time
  condition: []
  action:
    service: hassio.snapshot_full