##################
## TØRKETROMMEL ##
##################
- alias: 'Tørketrommel kjører'
  trigger:
    - platform: numeric_state
      entity_id: sensor.torketrommel_effekt
      above: '30'
      for:
        seconds: 30
  condition:
    condition: state
    entity_id: input_select.torketrommel
    state: 'Av'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.torketrommel
        option: 'Kjører'

- alias: 'Tørketrommel ferdig'
  trigger:
    - platform: numeric_state
      entity_id: sensor.torketrommel_effekt
      below: '7'
      for:
        seconds: 40
  condition:
    condition: state
    entity_id: input_select.torketrommel
    state: 'Kjører'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.torketrommel
        option: Ferdig
    - service: notify.magnus
      data:
        message: "Tørketrommel ferdig"
#        data:
#          inline_keyboard:
#            - 'Task 1:/command1, Task 2:/command2'
#            - 'Task 3:/command3, Task 4:/command4'
    - service: notify.mona
      data:
        message: "Tørketrommel ferdig"

- alias: 'Tørketrommel av'
  trigger:
    - platform: state
      entity_id: input_select.torketrommel
      to: 'Ferdig'
      for:
        seconds: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.torketrommel
        option: Av

#################
## VASKEMASKIN ##
#################
- alias: 'Vaskemaskin kjører'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vaskemaskin_effekt
      above: '20'
      for:
        seconds: 45
  condition:
    condition: state
    entity_id: input_select.vaskemaskin
    state: 'Av'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaskemaskin
        option: 'Kjører'

- alias: 'Vaskemaskin ferdig'
  trigger:
    - platform: numeric_state
      entity_id: sensor.vaskemaskin_effekt
      below: '2'
      for:
        seconds: 60
  condition:
    condition: state
    entity_id: input_select.vaskemaskin
    state: 'Kjører'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaskemaskin
        option: Ferdig
    - service: notify.magnus
      data:
        message: "Vaskemaskin ferdig"
    - service: notify.mona
      data:
        message: "Vaskemaskin ferdig"

- alias: 'Vaskemaskin av'
  trigger:
    - platform: state
      entity_id: input_select.vaskemaskin
      to: 'Ferdig'
      for:
        seconds: 30
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.vaskemaskin
        option: Av


#######################
## VARMTVANNSBEREDER ##
#######################
- alias: 'VVB av'
  trigger:
    - platform: numeric_state
      entity_id: sensor.electricity_price_furulien_18_percent
      above: 75
  condition:
    condition: state
    entity_id: switch.varmtvannsbereder
    state: 'on'
    for:
      minutes: 120
  action:
    - service: switch.turn_off
      entity_id: switch.varmtvannsbereder
    - service : input_select.select_option
      data:
        entity_id: input_select.vvb
        option: Av


- alias: 'VVB auto på'
  trigger:
    - platform: state
      entity_id: switch.varmtvannsbereder
      to: 'off'
      for:
        minutes: 150
  action:
    - service: switch.turn_on
      entity_id: switch.varmtvannsbereder
    - service: input_select.select_option
      data:
        entity_id: input_select.vvb
        option: På

##################
## TØRKETROMMEL ##
##################
- alias: 'Oppvask kjører'
  trigger:
    - platform: numeric_state
      entity_id: sensor.oppvaskmaskin_effekt
      above: '5'
      for:
        seconds: 30
  condition:
    condition: state
    entity_id: input_select.oppvask
    state: 'Av'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.oppvask
        option: 'Kjører'

- alias: 'Oppvask ferdig'
  trigger:
    - platform: numeric_state
      entity_id: sensor.oppvaskmaskin_effekt
      below: '7'
      for:
        minutes: 14
  condition:
    condition: state
    entity_id: input_select.oppvask
    state: 'Kjører'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.oppvask
        option: Ferdig
    - service: notify.magnus
      data:
        message: "Oppvaskmaskin ferdig"
    - service: notify.mona
      data:
        message: "Oppvaskmaskin ferdig"

- alias: 'Oppvaskmaskin av'
  trigger:
    - platform: state
      entity_id: input_select.oppvask
      to: 'Ferdig'
      for:
        seconds: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.oppvask
        option: Av