substitutions:
  devicename: benkelys
  upper_devicename: Benkelys

esphome:
  name: "$devicename"
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time
##############################################################

sensor:
  - platform: uptime
    name: "$upper_devicename Uptime"

text_sensor:
  - platform: version
    name: "$upper_devicename version"

switch:
  - platform: restart
    name: "$upper_devicename Restart"

binary_sensor:
  - platform: gpio
    id: button
    name: "$upper_devicename Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: light_benkelys

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: monochromatic
    output: green_led
    id: led
  - platform: binary
    name: "$upper_devicename"
    output: relay
    id: "light_$devicename"