substitutions:
  devicename: film_button_esp
  upper_devicename: Film Button ESP

esphome:
  name: "$devicename"
  platform: ESP8266
  board: nodemcuv2

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
api:
  password: !secret api_password
ota:
  password: !secret ota_password

##############################################################

binary_sensor:
  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
      inverted: true
    name: "Movie Button"
    filters:
      - delayed_off: 500ms
    on_press:
      then:
        - switch.turn_off: ring
    on_release:
      then:
        - switch.turn_on: ring

sensor:
## WiFi signal strenght sensor ##
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 60s

## Device firmware sensor ##
text_sensor:
  - platform: version
    name: "$upper_devicename Version"

## Switch to restart the device ##
switch:
  - platform: restart
    name: "$upper_devicename Restart"

  - platform: gpio
    pin: D8
    id: ring
    name: "Button Ring Light"
    internal: true
    restore_mode: RESTORE_DEFAULT_ON