substitutions:
  devicename: gangspot
  upper_devicename: Gangspot

esphome:
  name: "$devicename"
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

######################################################################

sensor:
  - platform: uptime
    name: "$upper_devicename Uptime"

  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    change_mode_every: 2
    power:
      name: "$upper_devicename Effekt"
      unit_of_measurement: W
      id: ${devicename}_power
      filters:
        - calibrate_linear:
            - 0 -> 0.9
            - 6.2 -> 7.5
            - 12.4 -> 14.96
            - 124.1 -> 145.5
            - 415 -> 487
            - 693 -> 810
            - 819 -> 960
            - 900 -> 1050
            - 1235 -> 1446
            - 1439 -> 1680
        - lambda: if (x < (1 + 0.915)) return 0; else return (x - 0.915);
    update_interval: 5s

  - platform: total_daily_energy
    name: "$upper_devicename Dagsforbruk"
    power_id: ${devicename}_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

text_sensor:
  - platform: version
    name: "$upper_devicename version"

binary_sensor:
  - platform: gpio
    id: button
    name: "$upper_devicename Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - light.toggle: "light_$devicename"

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true
  - platform: gpio
    pin: GPIO12
    id: relay

light:
  - platform: binary
    name: "$upper_devicename"
    output: relay
    id: "light_$devicename"