substitutions:
  devicename: gang_touch
  upper_devicename: Gang Touch

esphome:
  name: "$devicename"
  platform: ESP32
  board: nodemcu-32s

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
api:
  password: !secret api_password
ota:
  password: !secret ota_password

##############################################################
binary_sensor:
  - platform: gpio
    pin: 21
    name: "Gang Touch"
    filters:
      - delayed_on: 40ms
      - delayed_off: 150ms
sensor:
## WiFi signal strenght sensor ##
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 60s

text_sensor:
## Device firmware sensor ##
  - platform: version
    name: "$upper_devicename Version"

switch:
## Switch to restart the device ##
  - platform: restart
    name: "$upper_devicename Restart"
##############################################################
