substitutions:
  devicename: garasjeport
  upper_devicename: GarasjePort

esphome:
  name: "$devicename"
  platform: ESP8266
  board: d1_mini

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
  baud_rate: 115200

api:

ota:

sensor:
  - platform: ultrasonic
    trigger_pin: D1
    echo_pin: D2
    name: "Garasjeport"
    update_interval: 2s
    timeout: 3m