substitutions:
  devicename: ina219
  upper_devicename: INA219

esphome:
  name: "$devicename"
  platform: ESP32
  board: nodemcu-32s

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
api:
  password: !secret api_password
ota:
  password: !secret ota_password

##############################################################
i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

sensor:
## WiFi signal strenght sensor ##
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 60s



  - platform: ina219
    current:
      name: "INA219 Current"
    power:
      name: "INA219 Power"
    bus_voltage:
      name: "INA219 Bus Voltage"
    shunt_voltage:
      name: "INA219 Shunt Voltage"
    update_interval: 5s
    max_voltage: 26.0V
    max_current: 3.2A
    shunt_resistance: 0.1 ohm



## Device firmware sensor ##
text_sensor:
  - platform: version
    name: "$upper_devicename Version"

## Switch to restart the device ##
switch:
  - platform: restart
    name: "$upper_devicename Restart"
##############################################################
