substitutions:
  devicename: kjoleskap
  upper_devicename: Kjoleskap

esphome:
  name: "$devicename"
  platform: ESP8266
  board: esp8285

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO04
    cf1_pin: GPIO05
    change_mode_every: 2
    update_interval: 5s

    current:
      name: "$upper_devicename Current"
      unit_of_measurement: A
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0.0 -> 0.013
            - 0.08208 -> 0.071
            - 1.34223 -> 1.066
            - 5.57170 -> 4.408
            - 6.69184 -> 5.259
            - 6.97187 -> 5.540

    voltage:
      name: "$upper_devicename Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 602.87506 -> 229.9
            - 609.8 -> 232.8
    power:
      name: "$upper_devicename Effekt"
      unit_of_measurement: W
      id: ${devicename}_effekt
      filters:
        - calibrate_linear:
            - 4.1 -> 0.75
            - 9.3 -> 1.65
            - 16.5 -> 2.85
            - 87 -> 14.5
            - 938 -> 157
            - 1799 -> 303
            - 1816 -> 304.8
            - 6228 -> 1045
            - 9414 -> 1580
            - 10800 -> 1815
        - lambda: if (x < (1 + 1.4)) return 0; else return (x - 1.4);

  - platform: total_daily_energy
    name: "$upper_devicename Daily Energy"
    power_id: ${devicename}_effekt
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 10s

  - platform: uptime
    name: "$upper_devicename Uptime"

text_sensor:
  - platform: version
    name: "$upper_devicename version"

binary_sensor:
  - platform: gpio
    name: "$upper_devicename Button"
    pin:
      number: GPIO3
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    id: relay
    name: "$upper_devicename Switch"
    pin: GPIO14
    restore_mode: ALWAYS_ON
    on_turn_on:
      - light.turn_on: led
    on_turn_off:
      - light.turn_off: led

  - platform: restart
    name: "$upper_devicename Restart"

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO1
      inverted: true

light:
  - platform: monochromatic
    output: state_led
    id: led

status_led:
  pin:
    number: GPIO13
    inverted: true