substitutions:
  devicename: komfyr
  upper_devicename: Komfyr

esphome:
  comment: "Sonoff POW R1"
  name: "$devicename"
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

######################################################################
switch:
  - platform: gpio
    internal: true
    id: relay
    name: "$upper_devicename Switch"
    pin: GPIO12
    restore_mode: ALWAYS_ON

sensor:
  - platform: hlw8012
    sel_pin: 5
    cf_pin: 14
    cf1_pin: 13
    update_interval: 5s
    change_mode_every: 2
    power:
      name: "$upper_devicename Power"
      unit_of_measurement: W
      id: ${devicename}_power
      filters:
        - calibrate_linear:
            - 0 -> 0.9
            - 6.2 -> 7.5
            - 12.4 -> 14.96
            - 124.1 -> 145.5
            - 415 -> 487
            - 693 -> 810
            - 819 -> 960
            - 900 -> 1050
            - 1235 -> 1446
            - 1439 -> 1680
        - lambda: if (x < (1 + 0.915)) return 0; else return (x - 0.915);

  - platform: total_daily_energy
    name: "$upper_devicename Daily Energy"
    power_id: ${devicename}_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO13
      inverted: true