substitutions:
  devicename: meonode_stue
  upper_devicename: MEONode Stue

esphome:
  name: "$devicename"
  platform: ESP8266
  board: nodemcuv2

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
api:
  password: !secret api_password
ota:
  password: !secret ota_password

##############################################################

binary_sensor:
## The connected VMA314 PIR sensor ##
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLDOWN_16
    name: "$upper_devicename Bevegelse"
    device_class: motion

sensor:
## The connected AM2302 Temperature/Humidity sensor ##
  - platform: dht
    pin: D7
    model: AM2302
    temperature:
      name: "$upper_devicename Temperatur"
      filters:
        - offset: -4.1
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
    humidity:
      name: "$upper_devicename Fuktighet"
    update_interval: 10s

## Switch to restart the device ##
switch:
  - platform: restart
    name: "$upper_devicename Restart"