substitutions:
  devicename: rfidreader
  upper_devicename: RFIDreader

esphome:
  name: "$devicename"
  platform: ESP8266
  board: d1_mini
  on_boot:
    - light.turn_on:
        id: activity_led
        brightness: 100%
        red: 0%
        blue: 0%
        green: 100%
    - delay: 2000ms
    - light.turn_off:
        id: activity_led

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
  baud_rate: 115200

api:

ota:
  
spi:
  clk_pin: D3
  miso_pin: D2
  mosi_pin: D1

pn532:
 cs_pin: D0
 update_interval: 1s
 on_tag:
   then:
    - text_sensor.template.publish:
       id: rfid_tag
       state: !lambda 'return x;'
    - homeassistant.event:
       event: esphome.rfid_read
       data_template: 
         message: !lambda 'return x;'
    - light.turn_on:
        id: activity_led
        brightness: 100%
        red: 0%
        green: 100%
        blue: 0%
    - delay: 150ms
    - light.turn_off:
        id: activity_led
    - delay: 90ms
    - light.turn_on:
        id: activity_led
        brightness: 100%
        red: 0%
        green: 100%
        blue: 0%
    - delay: 150ms
    - light.turn_off:
        id: activity_led
    - delay: 1500ms
    - text_sensor.template.publish:
       id: rfid_tag
       state: 'waiting'

output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: D4
      inverted: true

light:
  - platform: fastled_clockless
    chipset: WS2811
    pin: D4
    default_transition_length: 10ms
    num_leds: 1
    rgb_order: GRB
    id: activity_led
    restore_mode: ALWAYS_OFF
    name: "Activity LED"

text_sensor:
  - platform: template
    name: "RFID Tag"
    id: rfid_tag
  - platform: homeassistant
    name: ha_state
    entity_id: sensor.rfid_tag