substitutions:
  devicename: tagreader
  upper_devicename: TagReader

web_server:
  port: 80

esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini

#wifi insert your SSID and Your PWD once connected
wifi:
  ap:
    ssid: rfidreader
captive_portal:
# Enable logging
logger:
  baud_rate: 9600

ota:
  password: !secret ESP_OTA_PWD