substitutions:
  devicename: varmekabler_bad
  upper_devicename: Varmekabler Bad

esphome:
  name: "$devicename"
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  reboot_timeout: 10min
  networks:
  - ssid: 'IoT2'
    password: !secret wifi_password

logger:
  baud_rate: 0

uart:
  rx_pin: RX
  baud_rate: 4800

api:
  password: !secret api_password
  reboot_timeout: 0s

ota:
  password: !secret ota_password

time:
  - platform: homeassistant
    id: homeassistant_time

######################################################################

sensor:
  - platform: wifi_signal
    name: "$upper_devicename WiFi Signal"
    update_interval: 10s

  - platform: uptime
    name: "$upper_devicename Uptime"

  - platform: cse7766
    current:
      name: "$upper_devicename Strom"
    voltage:
      name: "$upper_devicename Spenning"
    power:
      id: ${devicename}_power
      name: "$upper_devicename Power"
      unit_of_measurement: W
      accuracy_decimals: 1
      filters:
        - calibrate_linear:
            - 0.7 -> 1.7
            - 2.5 -> 3.9
            - 10 -> 11.9
            - 148.9 -> 157.4
            - 288 -> 303
            - 501 -> 525
            - 989.3 -> 1040
            - 1525 -> 1600
        - lambda: if (x < (1 + 0.8)) return 0; else return (x - 0.8);
    update_interval: 5s

  - platform: total_daily_energy
    name: "$upper_devicename Dagsforbruk"
    power_id: ${devicename}_power
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

text_sensor:
  - platform: version
    name: "$upper_devicename version"

switch:
  - platform: restart
    name: "$upper_devicename Restart"
  - platform: gpio
    name: ${upper_devicename}
    id: ${devicename}_Relay
    pin: GPIO12
    restore_mode: ALWAYS_ON